services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
